
#####################
# Bench Dockerfile #
#####################

FROM rust:1.46.0 as cntr
RUN rustup target add x86_64-unknown-linux-musl

# Add docker-pid binary
RUN curl -sL https://github.com/Mic92/docker-pid/releases/download/1.0.0/docker-pid-linux-amd64 \
      > /usr/bin/docker-pid && \
      chmod 755 /usr/bin/docker-pid

# Add cntr binary
RUN wget https://github.com/Mic92/cntr/releases/download/1.5.1/cntr-src-1.5.1.tar.gz && \
      tar -xvf cntr-src-1.5.1.tar.gz
WORKDIR  /cntr-src-1.5.1
RUN cargo build --release --target=x86_64-unknown-linux-musl || true 
RUN strip target/x86_64-unknown-linux-musl/release/cntr -o /usr/bin/cntr

# Set the base image
FROM    ubuntu:groovy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -qy \
        wget gdebi-core php php-zip make gcc python containerd

RUN wget https://github.com/phoronix-test-suite/phoronix-test-suite/releases/download/v10.4.0/phoronix-test-suite_10.4.0_all.deb 
RUN gdebi phoronix-test-suite_10.4.0_all.deb -n

RUN phoronix-test-suite install compilebench gzip iozone leveldb tiobench unpack-linux

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /root/
COPY --from=cntr /usr/bin/cntr /usr/bin/cntr
COPY --from=cntr /usr/bin/docker-pid /usr/bin/docker-pid
ENTRYPOINT bash
