
#####################
# Bench Dockerfile #
#####################

FROM rust:1.46.0 as cntr
RUN rustup target add x86_64-unknown-linux-musl

# Add cntr binary
RUN git clone https://github.com/Mic92/cntr.git
WORKDIR  /cntr
RUN cargo build --release --target=x86_64-unknown-linux-musl --examples
RUN strip target/x86_64-unknown-linux-musl/release/examples/cntrfs -o /usr/bin/cntrfs

# Set the base image
FROM    ubuntu:groovy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -qy \
        wget gdebi-core php php-zip make gcc python 

RUN wget https://github.com/phoronix-test-suite/phoronix-test-suite/releases/download/v10.4.0/phoronix-test-suite_10.4.0_all.deb 
RUN gdebi phoronix-test-suite_10.4.0_all.deb -n

RUN phoronix-test-suite install benchmark disk

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /root/
COPY --from=cntr /usr/bin/cntrfs /usr/bin/cntrfs
ENTRYPOINT bash
